# Jekyll configuration
title: Marthyi.GitHub.io 
name: Marthyi.GitHub.io 
description: Welcome to Marthyi.GitHub.io！

## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "fr" 

paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
